import TanstackQueryProvider from "@/components/provider/TanstackQueryProvider";
import "./globals.css";
import Layout from "@/components/layout/Layout";

export const metadata = {
  title: "آژانس مسافرتی تورینو | برگزار کننده تورهای داخلی و خارجی",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="font-yekanbakh  ">
        <TanstackQueryProvider>
          <Layout>{children}</Layout>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
